# classification algorithm summary

## Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing the dataset

In [3]:
df = pd.read_csv("Social_Network_Ads.csv")
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [4]:
print(x.shape)
print(y.shape)

(400, 2)
(400,)


## Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size = .25, random_state=0)

## Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train_x = sc.fit_transform(train_x)
test_x = sc.transform(test_x)

## Training the SVM model on the Training set

In [7]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [8]:
models=[]
models.append(('linear SVM', SVC(kernel='linear', random_state=0)))
models.append(('rbf SVM', SVC(kernel='rbf', random_state=0)))
models.append(('Random Forest', RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)))
models.append(('Naive Bayes', GaussianNB()))
models.append(('logistic regression', LogisticRegression(random_state=0)))
models.append(('KNN', KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)))
models.append(('Decision Tree', DecisionTreeClassifier(criterion='entropy', random_state=0)))

In [9]:
classifier = []
for i in range(len(models)):
  print("training {0} model...".format(models[i][0]))
  classifier.append(models[i][1])
  classifier[i].fit(train_x, train_y)

print("Done!")

training linear SVM model...
training rbf SVM model...
training Random Forest model...
training Naive Bayes model...
training logistic regression model...
training KNN model...
training Decision Tree model...
Done!


## Making the Confusion Matrix

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score

accuracy = []

for i in range(len(models)):
  pred_y = classifier[i].predict(test_x)
  cm = confusion_matrix(test_y, pred_y)
  accuracy.append(accuracy_score(test_y, pred_y))
  print("model {0}".format(models[i][0]))
  print("confusion matrix")
  print(cm)
  print("accuracy score {0}\n".format(accuracy[i]))

print(models[accuracy.index(max(accuracy))][0], "is the best")

model linear SVM
confusion matrix
[[66  2]
 [ 8 24]]
accuracy score 0.9

model rbf SVM
confusion matrix
[[64  4]
 [ 3 29]]
accuracy score 0.93

model Random Forest
confusion matrix
[[63  5]
 [ 4 28]]
accuracy score 0.91

model Naive Bayes
confusion matrix
[[65  3]
 [ 7 25]]
accuracy score 0.9

model logistic regression
confusion matrix
[[65  3]
 [ 8 24]]
accuracy score 0.89

model KNN
confusion matrix
[[64  4]
 [ 3 29]]
accuracy score 0.93

model Decision Tree
confusion matrix
[[62  6]
 [ 3 29]]
accuracy score 0.91

rbf SVM is the best
