# classification algorithm summary

## Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing the dataset

In [12]:
df = pd.read_csv("Data_RG.csv")
x = df.iloc[:, :-1].values
y = df.iloc[:, -1:].values

In [13]:
print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[[463.26]
 [444.37]
 [488.56]
 ...
 [429.57]
 [435.74]
 [453.28]]


## Splitting the dataset into the Training set and Test set

In [14]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size = .2, random_state=0)

## Feature Scaling

In [15]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
train_scx = sc_x.fit_transform(train_x)
train_scy = sc_y.fit_transform(train_y)

## Training the SVM model on the Training set

In [22]:
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

In [23]:
poly_reg = PolynomialFeatures(degree=4)
x_poly = poly_reg.fit_transform(train_x)

In [24]:
models=[]
models.append(('rbf SVR', SVR(kernel='rbf')))
models.append(('Random Forest', RandomForestRegressor(n_estimators=10, random_state=0)))
models.append(('linear regression', LinearRegression()))
models.append(('multiple regression', LinearRegression()))
models.append(('decision tree', DecisionTreeRegressor(random_state=0)))

In [26]:
regressor = []
for i in range(len(models)):
  print("training {0} model...".format(models[i][0]))
  regressor.append(models[i][1])
  if i == 0:
    regressor[i].fit(train_scx, train_scy)
  elif i == 2:
    regressor[i].fit(x_poly, train_y)
  else:
    regressor[i].fit(train_x, train_y)
print("Done!")

training rbf SVR model...


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


training Random Forest model...


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


training linear regression model...
training multiple regression model...
training decision tree model...
Done!


## Making the Confusion Matrix

In [28]:
from sklearn.metrics import r2_score

accuracy = []

for i in range(len(models)):
  if i == 0:
    pred_y = sc_y.inverse_transform(regressor[i].predict(sc_x.transform(test_x)))
  elif i == 2:
    pred_y = regressor[i].predict(poly_reg.transform(test_x))
  else:
    pred_y = regressor[i].predict(test_x)
  print("model {0}, score: {1}".format(models[i][0], r2_score(test_y, pred_y)))
  accuracy.append(r2_score(test_y, pred_y))
  print()

print(models[accuracy.index(max(accuracy))][0], "is the best")

model rbf SVR, score: 0.9480784049986258

model Random Forest, score: 0.9615980699813017

model linear regression, score: 0.9458193772176482

model multiple regression, score: 0.9325315554761302

model decision tree, score: 0.9226091050550043

Random Forest is the best
